### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by ashvalejohn** [ashvalejohn/catalog-app#1]
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x] Styling
- [x] Smooth, bug-free navigation
- [x] Adequate and appropriate seeds

**Comment by mladenoff** [comment]
I am getting some weirdness with your modal on your live site. I can't get it to close when I click outside of it.

**Comment by ashvalejohn** [comment]
Fixed.

**Comment by mladenoff** [comment]
The entire modal is getting focus when it opens (should be visible as blue highlighting around modal). Look what happens when you click on the _Email_ box. You will want focus to be there upon open. It also returns focus to the modal (rather than _Email_) when you click one of the links to toggle sign up/log in.

**Comment by ashvalejohn** [comment]
Fixed.

**Comment by mladenoff** [comment]
LGTM
